# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.1.1
_src_path: gh:algorandfoundation/algokit-react-frontend-template
author_email: prathamesh.mutkure@reap.hk
author_name: Prathamesh Mutkure
preset_name: starter
project_name: algorand-agent-pass-frontend

